services:
  - type: web
    name: roadway-project-selector
    env: static
    rootDir: app
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
